version: '3.8'

services:
  dev:
    container_name: nest-dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    container_name: nest-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - nestjs-network
networks:
  nestjs-network:
volumes:
  mysqldata: